### ISSUE TITLE
Character animations

### ISSUE THREAD

**Issue by PTSwordz** [ArthurKyleEstuar/Debteria-SHIT#31]
Warrior
- [ ] - A Attacks
- [ ] - B Attacks
- [ ] - C Attacks
- [ ] - Idle
- [ ] - Run
- [ ] - Walk
- [ ] - Jump
- [ ] - Fall
- [ ] - Hurt
- [ ] - Death
Mage
- [ ] - A Attacks
- [ ] - B Attacks
- [ ] - C Attacks
- [ ] - Idle
- [ ] - Run
- [ ] - Walk
- [ ] - Jump
- [ ] - Fall
- [ ] - Hurt
- [ ] - Death

**Comment by ArthurKyleEstuar** [comment]
Define what char anims, please always enumerate
